# NUMPY : Package for Multidimensional Array
## Vector (1d)
## Matrix (2d or 1d)

## Create an array

In [3]:
import numpy as np

In [4]:
simple_list = [6,4,5]
np.array(simple_list)

array([6, 4, 5])

In [5]:
arr = np.array([6,4,5])
arr

array([6, 4, 5])

In [6]:
list_of_lists = [1,2,3],[4,5,6],[7,8,9]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(10,32)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31])

In [7]:
np.arange(10,83,8)

array([10, 18, 26, 34, 42, 50, 58, 66, 74, 82])

In [8]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [12]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [15]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [16]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [17]:
np.random.rand(2,4)

array([[0.13565568, 0.44843759, 0.40278394, 0.6092031 ],
       [0.14463557, 0.18157015, 0.6953697 , 0.44308948]])

In [7]:
np.random.randn(2,4)

array([[-0.15985879,  1.47951377,  0.41878452,  1.29238257],
       [ 2.14639817,  0.54620094,  0.79947623, -0.14535372]])

In [23]:
np.random.rand(2,5)

array([[0.93092562, 0.73653931, 0.24761634, 0.96879311, 0.17056605],
       [0.5002335 , 0.43140967, 0.85370816, 0.57319976, 0.47831918]])

In [24]:
np.random.randint(0,20,15)

array([19,  6, 15,  2,  5, 14, 14, 16,  1,  1, 11,  5, 15,  4,  5])

In [25]:
np.random.randint(10,100,15)

array([17, 73, 42, 55, 12, 32, 87, 11, 66, 80, 17, 17, 34, 80, 54])

In [26]:
np.random.randint(10,65,80)

array([32, 55, 26, 19, 32, 39, 45, 15, 47, 29, 55, 22, 58, 47, 60, 31, 12,
       24, 42, 29, 11, 44, 31, 48, 43, 30, 15, 28, 18, 64, 36, 29, 31, 12,
       34, 52, 20, 48, 38, 13, 43, 19, 64, 57, 57, 41, 62, 26, 56, 15, 46,
       50, 49, 27, 60, 37, 64, 19, 22, 55, 43, 36, 34, 11, 12, 20, 49, 36,
       28, 32, 37, 42, 42, 36, 60, 18, 15, 23, 61, 26])

In [10]:
import numpy as np

In [11]:
sample_array = np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [12]:
rand_array = np.random.randint(0,10,5)
rand_array

array([9, 0, 0, 2, 9])

In [14]:
sample_array.min()

2

In [15]:
sample_array.argmin()

0

In [16]:
rand_array.argmin()

1

In [17]:
rand_array.max()

9

In [18]:
rand_array.argmax()

0

In [19]:
sample_array.argmax()

17

In [20]:
sample_array.dtype

dtype('int32')

In [24]:
np.random.randint(4,[10,5,15])

array([7, 4, 4])

In [28]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
a=np.random.rand(2,3)
a

array([[0.85317311, 0.71282705, 0.08397115],
       [0.16406891, 0.01075503, 0.73634831]])

In [30]:
a.T

array([[0.85317311, 0.16406891],
       [0.71282705, 0.01075503],
       [0.08397115, 0.73634831]])

In [31]:
sample_array=np.arange(10,28)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27])

In [32]:
sample_array = sample_array.reshape(6,3)
sample_array

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

In [33]:
sample_array[5]=100
sample_array

array([[ 10,  11,  12],
       [ 13,  14,  15],
       [ 16,  17,  18],
       [ 19,  20,  21],
       [ 22,  23,  24],
       [100, 100, 100]])

In [34]:
sample_array = np.arange(10,100)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [35]:
sample_array[1:12]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [36]:
subset_sample_array= sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [37]:
sample_array[:] = 1001
sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001, 1001,
       1001, 1001])

## Two-Dimensional array

In [2]:
import numpy as np

In [40]:
sample_matrix = np.array([[45,78,98,12],[65,1,51,34],[11,89,70,32]])
sample_matrix

array([[45, 78, 98, 12],
       [65,  1, 51, 34],
       [11, 89, 70, 32]])

In [41]:
sample_matrix[2,3]

32

In [42]:
sample_matrix[2][3]

32

In [43]:
sample_matrix[1][2]

51

In [44]:
sample_matrix[:,2]

array([98, 51, 70])

In [45]:
sample_matrix[1:3,2:4]

array([[51, 34],
       [70, 32]])

In [46]:
sample_matrix[1:,2:]

array([[51, 34],
       [70, 32]])

In [47]:
sample_matrix[:,(3,2)]

array([[12, 98],
       [34, 51],
       [32, 70]])

In [ ]:
sample_matrix[1,1]

In [ ]:
sample_matrix[2]

In [3]:
sample_array = np.arange(5,40)
sample_array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39])

In [4]:
sample_array + sample_array

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78])

In [5]:
np.exp(sample_array)

array([1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13, 2.90488497e+13, 7.89629602e+13,
       2.14643580e+14, 5.83461743e+14, 1.58601345e+15, 4.31123155e+15,
       1.17191424e+16, 3.18559318e+16, 8.65934004e+16])

In [6]:
np.sqrt(sample_array)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481,
       5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
       5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ])

In [7]:
np.log(sample_array)

array([1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
       2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
       3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583,
       3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
       3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165])

In [8]:
np.max(sample_array)

39

In [9]:
np.min(sample_array)

5

In [10]:
np.argmax(sample_array)

34

In [11]:
np.argmin(sample_array)

0

In [12]:
np.square(sample_array)

array([  25,   36,   49,   64,   81,  100,  121,  144,  169,  196,  225,
        256,  289,  324,  361,  400,  441,  484,  529,  576,  625,  676,
        729,  784,  841,  900,  961, 1024, 1089, 1156, 1225, 1296, 1369,
       1444, 1521], dtype=int32)

In [13]:
np.std(sample_array)

10.099504938362077

In [14]:
np.var(sample_array)

102.0

In [15]:
np.mean(sample_array)

22.0

In [16]:
array= np.random.randn(3,4)
array

array([[ 1.05967556,  0.78146266, -0.09498498, -1.2507958 ],
       [-0.9251966 , -0.63269192, -2.19538697,  0.6721199 ],
       [-1.13834628, -0.50138402,  0.28875074, -1.44343967]])

In [17]:
np.round(array,decimals=4)

array([[ 1.0597,  0.7815, -0.095 , -1.2508],
       [-0.9252, -0.6327, -2.1954,  0.6721],
       [-1.1383, -0.5014,  0.2888, -1.4434]])

In [18]:
Fruits = np.array(["apple","mango","banana","grapes","apple","mango"])
Fruits

array(['apple', 'mango', 'banana', 'grapes', 'apple', 'mango'],
      dtype='<U6')

In [19]:
np.unique(Fruits)

array(['apple', 'banana', 'grapes', 'mango'], dtype='<U6')

# Pandas

In [2]:
import pandas as pd

In [3]:
labels = ['a','b','c','d'] 

In [4]:
list = [25,30,10,5]

In [5]:
import numpy as np

In [7]:
array = np.array([1,2,3,4])
array

array([1, 2, 3, 4])

In [10]:
dict = {'p':10,'q':20,'r':30,'s':40}

In [12]:
pd.Series(list) 

0    25
1    30
2    10
3     5
dtype: int64

In [13]:
pd.Series(list,index=labels)

a    25
b    30
c    10
d     5
dtype: int64

In [14]:
pd.Series(list,labels)

a    25
b    30
c    10
d     5
dtype: int64

In [15]:
pd.Series(dict)

p    10
q    20
r    30
s    40
dtype: int64

## Pandas dataframe and indexing

In [16]:
sports1 = pd.Series([1,2,3,4], index=['cricket','hockey','football','rugby'])
sports1

cricket     1
hockey      2
football    3
rugby       4
dtype: int64

In [17]:
sports1['football']

3

In [18]:
sports2 = pd.Series([11,12,13,14], index= ['cricket','football','rugby','tennis'])
sports2

cricket     11
football    12
rugby       13
tennis      14
dtype: int64

In [19]:
sports1 + sports2

cricket     12.0
football    15.0
hockey       NaN
rugby       17.0
tennis       NaN
dtype: float64

In [25]:
df1 = pd.DataFrame(np.random.rand(9,5),index='A B C D E F G H I'.split(),columns='score1 score2 score3 score4 score5'.split())
df1

score1    score2    score3    score4    score5
A  0.065090  0.391388  0.015397  0.030796  0.003283
B  0.057678  0.840337  0.968664  0.735187  0.802539
C  0.180756  0.705771  0.613304  0.706583  0.352566
D  0.790396  0.920323  0.999232  0.962334  0.673547
E  0.775015  0.990165  0.971184  0.734930  0.647837
F  0.141234  0.779646  0.391199  0.362190  0.777558
G  0.854621  0.558345  0.475575  0.214302  0.199221
H  0.655528  0.549695  0.816887  0.474728  0.580303
I  0.226356  0.204928  0.239071  0.875984  0.326265

In [26]:
df1['score3']

A    0.015397
B    0.968664
C    0.613304
D    0.999232
E    0.971184
F    0.391199
G    0.475575
H    0.816887
I    0.239071
Name: score3, dtype: float64

In [29]:
df1[["score1","score2","score3"]]

score1    score2    score3
A  0.065090  0.391388  0.015397
B  0.057678  0.840337  0.968664
C  0.180756  0.705771  0.613304
D  0.790396  0.920323  0.999232
E  0.775015  0.990165  0.971184
F  0.141234  0.779646  0.391199
G  0.854621  0.558345  0.475575
H  0.655528  0.549695  0.816887
I  0.226356  0.204928  0.239071

In [30]:
df1['score6'] = df1['score1']+df1['score5']
df1

score1    score2    score3    score4    score5    score6
A  0.065090  0.391388  0.015397  0.030796  0.003283  0.068372
B  0.057678  0.840337  0.968664  0.735187  0.802539  0.860217
C  0.180756  0.705771  0.613304  0.706583  0.352566  0.533322
D  0.790396  0.920323  0.999232  0.962334  0.673547  1.463943
E  0.775015  0.990165  0.971184  0.734930  0.647837  1.422852
F  0.141234  0.779646  0.391199  0.362190  0.777558  0.918792
G  0.854621  0.558345  0.475575  0.214302  0.199221  1.053842
H  0.655528  0.549695  0.816887  0.474728  0.580303  1.235831
I  0.226356  0.204928  0.239071  0.875984  0.326265  0.552621

In [31]:
df1.drop('score5',axis=1)

score1    score2    score3    score4    score6
A  0.065090  0.391388  0.015397  0.030796  0.068372
B  0.057678  0.840337  0.968664  0.735187  0.860217
C  0.180756  0.705771  0.613304  0.706583  0.533322
D  0.790396  0.920323  0.999232  0.962334  1.463943
E  0.775015  0.990165  0.971184  0.734930  1.422852
F  0.141234  0.779646  0.391199  0.362190  0.918792
G  0.854621  0.558345  0.475575  0.214302  1.053842
H  0.655528  0.549695  0.816887  0.474728  1.235831
I  0.226356  0.204928  0.239071  0.875984  0.552621

In [ ]:
df1.drop('E',axis=0)

In [18]:
df2 = {'ID':[101,102,103,104,105],'NAME':['John','Michael','Kevin','Shawn','Cooper'],'Profit':[21,55,61,92,152]}
df2 = pd.DataFrame(df2)
df2

ID     NAME  Profit
0  101     John      21
1  102  Michael      55
2  103    Kevin      61
3  104    Shawn      92
4  105   Cooper     152

In [19]:
df2['NAME']

0       John
1    Michael
2      Kevin
3      Shawn
4     Cooper
Name: NAME, dtype: object

In [21]:
df2[['NAME','ID']]

NAME   ID
0     John  101
1  Michael  102
2    Kevin  103
3    Shawn  104
4   Cooper  105

### Read the data from the excel/CSV file

In [17]:
dfc = pd.read_excel("Class 12.1 - charts class 2.xlsx")
dfc

Months  Sales
0    Jan  67395
1    Feb  25235
2    Mar  77651
3    Apr  55933
4    May  27057
5    Jun  24997
6    Jul  63859
7    Aug  36862

In [29]:
df = pd.read_csv("u.user.csv")
df

user_id|age|gender|occupation|zip_code
0                  1|24|M|technician|85711
1                       2|53|F|other|94043
2                      3|23|M|writer|32067
3                  4|24|M|technician|43537
4                       5|33|F|other|15213
..                                     ...
938                 939|26|F|student|33319
939           940|32|M|administrator|02215
940                 941|20|M|student|97229
941               942|48|F|librarian|78209
942                 943|22|M|student|77841

[943 rows x 1 columns]