# NUMPY : Package for Multidimensional Array
## Vector (1d)
## Matrix (2d or 1d)

## Create an array

In [3]:
import numpy as np

In [5]:
simple_list = [6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [6]:
arr = np.array([6,7,9])
arr

array([6, 7, 9])

In [7]:
list_of_lists = [1,2,3],[4,5,6],[7,8,9]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(10,32)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31])

In [9]:
np.arange(10,83,8)

array([10, 18, 26, 34, 42, 50, 58, 66, 74, 82])

In [10]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros(6,dtype=int)

array([0, 0, 0, 0, 0, 0])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [14]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [20]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [22]:
np.eye(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [23]:
np.random.rand(2,4)

array([[0.27344395, 0.82613289, 0.36212107, 0.88916368],
       [0.63112889, 0.95763235, 0.40830338, 0.49355473]])

In [24]:
np.random.randn(2,4)

array([[ 0.99609342, -0.28987683,  0.41690852, -0.91171865],
       [-0.27996229,  0.12919205, -0.87517736,  1.01837657]])

In [25]:
np.random.rand(2,5)

array([[0.5818202 , 0.13050059, 0.25522746, 0.52807688, 0.41655495],
       [0.77115557, 0.84518831, 0.24389097, 0.65117191, 0.22027867]])

In [27]:
np.random.randint(0,10,15)

array([6, 6, 0, 3, 6, 7, 6, 3, 2, 6, 4, 4, 4, 4, 6])

In [28]:
np.random.randint(10,100,15)

array([29, 35, 68, 12, 64, 47, 60, 85, 13, 10, 65, 13, 84, 43, 86])

In [29]:
np.random.randint(20,56,100)

array([45, 38, 42, 42, 31, 52, 25, 51, 30, 36, 45, 28, 54, 37, 53, 49, 52,
       36, 33, 21, 44, 41, 48, 22, 55, 28, 23, 55, 25, 29, 30, 50, 22, 48,
       44, 43, 36, 32, 33, 39, 48, 50, 23, 47, 33, 28, 40, 42, 40, 33, 41,
       53, 38, 55, 51, 20, 45, 23, 39, 42, 25, 36, 29, 34, 32, 51, 49, 29,
       40, 33, 48, 26, 45, 50, 41, 30, 35, 31, 33, 35, 30, 32, 41, 36, 23,
       52, 44, 54, 23, 26, 38, 35, 32, 48, 23, 55, 34, 49, 39, 51])